[天池] 零基础入门推荐系统 - 新闻推荐x参考答案
========

## 数据下载

| 名称 | 大小 | Link |
|---|---|---|
| articles.csv | 9.89MB | http://tianchi-competition.oss-cn-hangzhou.aliyuncs.com/531842/articles.csv |
| articles_emb.csv | 973.15MB(MD5:1f8a7fc79e0ad13311e27e3408d0287b) | http://tianchi-competition.oss-cn-hangzhou.aliyuncs.com/531842/articles_emb.csv |
| testA_click_log.csv | 20.47MB | http://tianchi-competition.oss-cn-hangzhou.aliyuncs.com/531842/testA_click_log.csv |
| train_click_log.csv | 43.5MB | http://tianchi-competition.oss-cn-hangzhou.aliyuncs.com/531842/train_click_log.csv |

## 实验步骤

<div class="alert alert-block alert-info">
用 参考答案 试试
</div>

## 比赛说明

[零基础入门推荐系统【赛题理解+Baseline】Task1](https://tianchi.aliyun.com/notebook-ai/detail?postId=144449)

[零基础入门推荐系统【数据分析】Task2](https://tianchi.aliyun.com/notebook-ai/detail?postId=144451)

[零基础入门推荐系统【参考答案】](https://tianchi.aliyun.com/forum/postDetail?postId=166597)

<div class="alert alert-block alert-danger">
参考答案 score: x
</div>

## 数据加载与预处理

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

trn_click = pd.read_csv('/home/stdhi/dataset/exp02/train_click_log.csv')
trn_click = trn_click.rename(columns={'click_article_id': 'article_id'})
trn_click

,user_id,article_id,click_timestamp,click_environment,click_deviceGroup,click_os,click_country,click_region,click_referrer_type
0,199999,160417,1507029570190,4,1,17,1,13,1
1,199999,5408,1507029571478,4,1,17,1,13,1
2,199999,50823,1507029601478,4,1,17,1,13,1
3,199998,157770,1507029532200,4,1,17,1,25,5
4,199998,96613,1507029671831,4,1,17,1,25,5
...,...,...,...,...,...,...,...,...,...
1112618,33446,16346,1508212054157,4,3,2,1,25,1
1112619,0,30760,1508211672520,4,1,17,1,25,2
1112620,0,157507,1508211702520,4,1,17,1,25,2
1112621,199178,234481,1508211513583,4,3,2,1,25,2
1112622,199178,233578,1508211543583,4,3,2,1,25,2

In [3]:
item_df = pd.read_csv('/home/stdhi/dataset/exp02/articles.csv')
item_df

        article_id  category_id  created_at_ts  words_count
0                0            0  1513144419000          168
1                1            1  1405341936000          189
2                2            1  1408667706000          250
3                3            1  1408468313000          230
4                4            1  1407071171000          162
...            ...          ...            ...          ...
364042      364042          460  1434034118000          144
364043      364043          460  1434148472000          463
364044      364044          460  1457974279000          177
364045      364045          460  1515964737000          126
364046      364046          460  1505811330000          479

[364047 rows x 4 columns]

In [4]:
item_emb_df = pd.read_csv('/home/stdhi/dataset/exp02/articles_emb.csv')
item_emb_df

,article_id,emb_0,emb_1,emb_2,emb_3,emb_4,emb_5,emb_6,emb_7,emb_8,...,emb_240,emb_241,emb_242,emb_243,emb_244,emb_245,emb_246,emb_247,emb_248,emb_249
0,0,-0.161183,-0.957233,-0.137944,0.050855,0.830055,0.901365,-0.335148,-0.559561,-0.500603,...,0.321248,0.313999,0.636412,0.169179,0.540524,-0.813182,0.286870,-0.231686,0.597416,0.409623
1,1,-0.523216,-0.974058,0.738608,0.155234,0.626294,0.485297,-0.715657,-0.897996,-0.359747,...,-0.487843,0.823124,0.412688,-0.338654,0.320786,0.588643,-0.594137,0.182828,0.397090,-0.834364
2,2,-0.619619,-0.972960,-0.207360,-0.128861,0.044748,-0.387535,-0.730477,-0.066126,-0.754899,...,0.454756,0.473184,0.377866,-0.863887,-0.383365,0.137721,-0.810877,-0.447580,0.805932,-0.285284
3,3,-0.740843,-0.975749,0.391698,0.641738,-0.268645,0.191745,-0.825593,-0.710591,-0.040099,...,0.271535,0.036040,0.480029,-0.763173,0.022627,0.565165,-0.910286,-0.537838,0.243541,-0.885329
4,4,-0.279052,-0.972315,0.685374,0.113056,0.238315,0.271913,-0.568816,0.341194,-0.600554,...,0.238286,0.809268,0.427521,-0.615932,-0.503697,0.614450,-0.917760,-0.424061,0.185484,-0.580292
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
364042,364042,-0.055038,-0.962136,0.869436,-0.071523,-0.725294,0.434320,0.198312,-0.581154,0.702346,...,-0.410550,0.564252,-0.463959,0.167907,-0.480068,0.652090,0.380880,0.433195,-0.662455,-0.222850
364043,364043,-0.136932,-0.995472,0.991298,0.031871,-0.915621,-0.658517,0.633090,-0.564356,0.676551,...,-0.681986,-0.574185,-0.536908,0.688934,0.528204,0.162435,0.940364,0.989298,-0.761595,-0.414652
364044,364044,-0.251390,-0.976243,0.586097,0.643631,-0.663359,-0.093480,0.691553,-0.588281,0.902999,...,-0.162220,-0.242030,-0.476131,0.352132,-0.311279,0.460574,-0.653077,-0.143725,0.068093,-0.705010
364045,364045,0.224342,-0.923288,-0.381742,0.687890,-0.773911,-0.103629,-0.406486,0.246004,0.255191,...,-0.422999,0.390324,0.655911,-0.646753,-0.174031,0.698037,-0.317102,0.687132,-0.531512,0.010726
364046,364046,-0.257134,-0.994631,0.983792,-0.190975,-0.953720,-0.893823,0.708974,-0.557027,0.846842,...,-0.490481,-0.689666,-0.661846,0.490945,0.736526,0.667668,0.902130,0.983873,-0.838183,-0.179283

In [5]:
tst_click = pd.read_csv('/home/stdhi/dataset/exp02/testA_click_log.csv')
tst_click = tst_click.rename(columns={'click_article_id': 'article_id'})
tst_click

,user_id,article_id,click_timestamp,click_environment,click_deviceGroup,click_os,click_country,click_region,click_referrer_type
0,249999,160974,1506959142820,4,1,17,1,13,2
1,249999,160417,1506959172820,4,1,17,1,13,2
2,249998,160974,1506959056066,4,1,12,1,13,2
3,249998,202557,1506959086066,4,1,12,1,13,2
4,249997,183665,1506959088613,4,1,17,1,15,5
...,...,...,...,...,...,...,...,...,...
518005,221924,70758,1508211323220,4,3,2,1,25,2
518006,207823,331116,1508211542618,4,3,2,1,25,1
518007,207823,234481,1508211850103,4,3,2,1,25,1
518008,207823,211442,1508212189949,4,3,2,1,25,1
518009,207823,211401,1508212315718,4,3,2,1,25,1

In [6]:
trn_click = trn_click.merge(item_df, how='left', on=['article_id']).merge(item_emb_df, how='left', on=['article_id'])
trn_click.info()
trn_click

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1112623 entries, 0 to 1112622
Columns: 262 entries, user_id to emb_249
dtypes: float64(250), int64(12)
memory usage: 2.2 GB

,user_id,article_id,click_timestamp,click_environment,click_deviceGroup,click_os,click_country,click_region,click_referrer_type,category_id,...,emb_240,emb_241,emb_242,emb_243,emb_244,emb_245,emb_246,emb_247,emb_248,emb_249
0,199999,160417,1507029570190,4,1,17,1,13,1,281,...,-0.035396,0.430354,-0.034288,-0.431451,0.448716,-0.472527,0.015664,0.036806,-0.735547,0.374187
1,199999,5408,1507029571478,4,1,17,1,13,1,4,...,-0.180327,0.741544,0.510459,0.679252,0.139048,0.132182,0.778001,0.689793,-0.718781,0.075403
2,199999,50823,1507029601478,4,1,17,1,13,1,99,...,-0.062174,0.180814,-0.863296,-0.225812,0.639231,-0.194262,-0.146139,-0.050636,-0.347049,-0.006493
3,199998,157770,1507029532200,4,1,17,1,25,5,281,...,0.473601,0.414304,-0.102727,-0.642336,0.595225,0.056331,-0.076619,-0.080360,0.305069,0.591671
4,199998,96613,1507029671831,4,1,17,1,25,5,209,...,-0.045476,-0.002392,-0.499399,0.406291,0.245494,0.237506,-0.609123,-0.318237,0.244888,-0.254125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1112618,33446,16346,1508212054157,4,3,2,1,25,1,7,...,-0.085717,0.659098,-0.391408,-0.504780,-0.357616,-0.251946,-0.514955,-0.539085,0.338237,0.135095
1112619,0,30760,1508211672520,4,1,17,1,25,2,26,...,-0.391624,-0.306477,-0.020246,-0.731424,-0.060728,0.314857,0.092171,-0.680306,-0.203156,-0.419023
1112620,0,157507,1508211702520,4,1,17,1,25,2,281,...,0.568318,-0.078299,-0.759821,-0.580076,0.631641,0.010659,-0.193663,-0.268063,0.037685,0.443299
1112621,199178,234481,1508211513583,4,3,2,1,25,2,375,...,-0.327291,-0.009473,0.469663,-0.734911,-0.070421,-0.457637,0.518804,0.576141,0.763434,0.224886
1112622,199178,233578,1508211543583,4,3,2,1,25,2,375,...,-0.187841,-0.272049,0.139594,-0.233047,0.741024,0.133072,0.402566,0.813076,0.725003,-0.057481

In [8]:
tst_click = tst_click.merge(item_df, how='left', on=['article_id']).merge(item_emb_df, how='left', on=['article_id'])
tst_click.info()
tst_click

<class 'pandas.core.frame.DataFrame'>
Int64Index: 518010 entries, 0 to 518009
Columns: 515 entries, user_id to emb_249_y
dtypes: float64(500), int64(15)
memory usage: 2.0 GB

,user_id,article_id,click_timestamp,click_environment,click_deviceGroup,click_os,click_country,click_region,click_referrer_type,category_id_x,...,emb_240_y,emb_241_y,emb_242_y,emb_243_y,emb_244_y,emb_245_y,emb_246_y,emb_247_y,emb_248_y,emb_249_y
0,249999,160974,1506959142820,4,1,17,1,13,2,281,...,0.542530,0.420016,-0.853814,-0.446323,0.571061,-0.434621,-0.595428,-0.387516,-0.025463,0.240127
1,249999,160417,1506959172820,4,1,17,1,13,2,281,...,-0.035396,0.430354,-0.034288,-0.431451,0.448716,-0.472527,0.015664,0.036806,-0.735547,0.374187
2,249998,160974,1506959056066,4,1,12,1,13,2,281,...,0.542530,0.420016,-0.853814,-0.446323,0.571061,-0.434621,-0.595428,-0.387516,-0.025463,0.240127
3,249998,202557,1506959086066,4,1,12,1,13,2,327,...,0.287842,0.692896,0.629386,-0.581294,0.331619,0.935079,-0.334321,0.883088,-0.126423,0.471471
4,249997,183665,1506959088613,4,1,17,1,15,5,301,...,0.553232,-0.163560,0.317047,-0.148573,0.312323,-0.000999,0.376919,-0.536233,0.637864,-0.097233
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
518005,221924,70758,1508211323220,4,3,2,1,25,2,136,...,0.661538,0.179476,0.272950,0.161602,0.263826,0.561259,-0.447380,0.628560,0.017345,-0.001117
518006,207823,331116,1508211542618,4,3,2,1,25,1,436,...,-0.674498,0.629157,0.230168,0.545514,0.231907,-0.230112,0.658718,0.926906,-0.741672,0.720419
518007,207823,234481,1508211850103,4,3,2,1,25,1,375,...,-0.327291,-0.009473,0.469663,-0.734911,-0.070421,-0.457637,0.518804,0.576141,0.763434,0.224886
518008,207823,211442,1508212189949,4,3,2,1,25,1,340,...,0.607435,-0.254955,-0.841968,-0.733879,0.502279,-0.471380,-0.184428,-0.312847,0.234281,0.536178
518009,207823,211401,1508212315718,4,3,2,1,25,1,340,...,0.559095,-0.413456,-0.559281,-0.487295,0.252771,-0.178046,-0.248119,-0.145156,0.139226,0.184342

## 参考解答

### 导包

In [1]:
# import packages
import math
import gc
import pickle
import random
from datetime import datetime
from operator import itemgetter
import numpy as np
import pandas as pd
from collections import defaultdict
import collections
import os
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torch.nn.utils.rnn import pack_padded_sequence, pad_packed_sequence
import torch.nn.functional as F
from tqdm import tqdm
from time import time
from copy import deepcopy
import gc
import warnings

#warnings.filterwarnings('ignore')

data_path = '/home/stdhi/dataset/exp02/' # 天池平台路径
save_path = '/home/stdhi/dataset/exp02/'  # 天池平台路径

# 参数配置
emb_dim = 256
hidden_size = 512
max_len = 18
valid_num = 10000
mix_recall_num = 50

np.random.seed(1997)

### 读取采样或全量数据

In [7]:
def label_enc(click, col):
    uniq, nuniq = click[col].unique(), click[col].nunique()
    match = dict(zip(uniq, range(1, nuniq + 1)))
    click[col] = click[col].map(match)
    return click, match, nuniq

def construct_samples_train(train_click, valid_num=20000, max_len=19, model_name='srgnn'):
    train_click.sort_values("click_timestamp", inplace=True)

    # users = train_click.user_id.unique()
    # np.random.shuffle(users)
    # valid_users = users[:valid_num]
    valid_users = np.load('valid_users.npy')
    valid_click = train_click[train_click.user_id.isin(valid_users)]
    train_click = train_click[~train_click.user_id.isin(valid_users)]

    train_users, train_seqs, train_targets = [], [], []
    for user, val in tqdm(train_click.groupby('user_id')):
        hist_item = val['click_article_id'].values.tolist()
        # hist_time = val['click_timestamp'].values.tolist()
        hist_len = len(hist_item)
        if hist_len == 1:
            continue
        elif hist_len <= max_len + 1:
            for i in range(hist_len - 1):
                train_users.append(user), train_seqs.append(hist_item[:i + 1]), train_targets.append(hist_item[i + 1])
        else:
            for i in range(hist_len - max_len):
                train_users.append(user), train_seqs.append(hist_item[i:i + max_len]), train_targets.append(
                        hist_item[i + max_len])

    valid_users, valid_seqs, valid_targets = [], [], []
    for user, val in tqdm(valid_click.groupby('user_id')):
        hist_item = val['click_article_id'].values.tolist()
        # hist_time = val['click_timestamp'].values.tolist()
        hist_len = len(hist_item)
        if hist_len == 1:
            continue
        elif hist_len <= max_len + 1:
            for i in range(hist_len - 2):
                train_users.append(user), train_seqs.append(hist_item[:i + 1]), train_targets.append(hist_item[i + 1])
            valid_users.append(user), valid_seqs.append(hist_item[:-1]), valid_targets.append(hist_item[-1])
        else:
            for i in range(hist_len - max_len - 1):
                train_users.append(user), train_seqs.append(hist_item[i:i + max_len]), train_targets.append(
                        hist_item[i + max_len])
            valid_users.append(user), valid_seqs.append(hist_item[-(max_len + 1):-1]), valid_targets.append(hist_item[-1])

    save_path = '../samples_tmp/'
    if not os.path.exists(save_path):
        os.makedirs(save_path)

    train = (train_users, train_seqs, train_targets)
    np.savez(save_path + 'train_{}.npz'.format(model_name), users=train_users, seqs=train_seqs, targets=train_targets)
    del train_users, train_seqs, train_targets

    valid = (valid_users, valid_seqs, valid_targets)
    np.savez(save_path + 'valid_{}.npz'.format(model_name), users=valid_users, seqs=valid_seqs, targets=valid_targets)
    del valid_users, valid_seqs, valid_targets

    gc.collect()

    print(len(train[0]), len(valid[0]))

    return train, valid

def construct_samples_test(train, test_click, max_len=19):
    test_click.sort_values("click_timestamp", inplace=True)
    # train_users, train_seqs, train_targets = train[0], train[1], train[2]
    train_users, train_seqs, train_targets = list(train[0]), list(train[1]), list(train[2])
    test_users, test_seqs = [], []
    for user, val in tqdm(test_click.groupby('user_id')):
        hist_item = val['click_article_id'].values.tolist()
        # hist_time = val['click_timestamp'].values.tolist()
        hist_len = len(hist_item)
        if hist_len == 1:
            test_users.append(user), test_seqs.append(hist_item)
        elif hist_len == 2:
            train_users.append(user), train_seqs.append(hist_item[:-1]), train_targets.append(hist_item[-1])
            test_users.append(user), test_seqs.append(hist_item)
        elif hist_len <= max_len + 1:
            for i in range(hist_len - 1):
                train_users.append(user), train_seqs.append(hist_item[:i + 1]), train_targets.append(hist_item[i + 1])
            # train_users.append(user), train_seqs.append(hist_item[:-2]), train_targets.append(hist_item[-2])
            test_users.append(user), test_seqs.append(hist_item)
        else:
            for i in range(hist_len - max_len):
                train_users.append(user), train_seqs.append(hist_item[i:i + max_len]), train_targets.append(
                        hist_item[i + max_len])
            test_users.append(user), test_seqs.append(hist_item[-max_len:])

    train = (train_users, train_seqs, train_targets)
    del train_users, train_seqs, train_targets

    test = (test_users, test_seqs)
    del test_users, test_seqs
    gc.collect()

    print(len(train[0]), len(test[0]))

    return train, test

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

train_click = pd.read_csv(data_path + 'train_click_log.csv')
train_click, user_match, user_nuniq = label_enc(train_click, 'user_id')
users = train_click.user_id.unique()
np.random.shuffle(users)
valid_users = users[:valid_num]
#valid_users = users

np.save('valid_users.npy', valid_users)
train_click

,user_id,click_article_id,click_timestamp,click_environment,click_deviceGroup,click_os,click_country,click_region,click_referrer_type
0,1,160417,1507029570190,4,1,17,1,13,1
1,1,5408,1507029571478,4,1,17,1,13,1
2,1,50823,1507029601478,4,1,17,1,13,1
3,2,157770,1507029532200,4,1,17,1,25,5
4,2,96613,1507029671831,4,1,17,1,25,5
...,...,...,...,...,...,...,...,...,...
1112618,166554,16346,1508212054157,4,3,2,1,25,1
1112619,200000,30760,1508211672520,4,1,17,1,25,2
1112620,200000,157507,1508211702520,4,1,17,1,25,2
1112621,822,234481,1508211513583,4,3,2,1,25,2
1112622,822,233578,1508211543583,4,3,2,1,25,2

In [ ]:
class TrainDataset(Dataset):

    def __init__(self, data):
        self.data = data

    def __getitem__(self, index):
        return self.data[0][index], self.data[1][index], self.data[2][index]

    def __len__(self):
        return len(self.data[0])

def TrainDataLoader(data, bs=512):
    data_set = TrainDataset(data)
    data_loader = DataLoader(data_set, batch_size=bs, shuffle=True, collate_fn=collate_fn_train, drop_last=True)

    return data_loader


class ValiDataset(Dataset):

    def __init__(self, data, clicked_mask=True, click=None, item_nuniq=None):
        users, hists, targets = data
        df = pd.DataFrame(np.array(users).reshape(-1, 1), columns=['user'])

        self.clicked_mask = clicked_mask
        if self.clicked_mask:
            click = click[click.user_id.isin(np.unique(users))]
            mask_value = -1e10
            tmp = click.groupby('user_id')['click_article_id'].agg(lambda x: list(x)[:-1]).reset_index()
            tmp.columns = ['user', 'total_history']
            df = df.merge(tmp, on='user', how='left')
            clicked_mask_matrix = torch.ones((df.shape[0], item_nuniq))
            for i, row in tqdm(enumerate(df['total_history'].values)):
                for item in row:
                    clicked_mask_matrix[i, item - 1] = mask_value
            del tmp
            gc.collect()
            self.data = (users, hists, targets, clicked_mask_matrix)
        else:
            self.data = (users, hists, targets)
        del data, df
        gc.collect()

    def __getitem__(self, idx):
        if self.clicked_mask:
            return self.data[0][idx], self.data[1][idx], self.data[2][idx], self.data[3][idx]
        else:
            return self.data[0][idx], self.data[1][idx], self.data[2][idx]

    def __len__(self):
        return len(self.data[0])

def ValiDataLoader(data, clicked_mask=True, click=None, item_nuniq=None, bs=512):
    data_set = ValiDataset(data, clicked_mask, click, item_nuniq)
    data_loader = DataLoader(data_set, batch_size=bs, shuffle=False, collate_fn=collate_fn_vali)

    return data_loader


class TestDataset(Dataset):

    def __init__(self, data, clicked_mask=True, click=None, item_nuniq=None):
        users, hists = data
        df = pd.DataFrame(np.array(users).reshape(-1, 1), columns=['user'])

        self.clicked_mask = clicked_mask
        if self.clicked_mask:
            mask_value = -1e10
            tmp = click.groupby('user_id')['click_article_id'].agg(list).reset_index()
            tmp.columns = ['user', 'total_history']
            df = df.merge(tmp, on='user', how='left')
            clicked_mask_matrix = torch.ones((df.shape[0], item_nuniq))
            for i, row in tqdm(enumerate(df['total_history'].values)):
                for item in row:
                    clicked_mask_matrix[i, item - 1] = mask_value
            del tmp
            gc.collect()
            self.data = (users, hists, clicked_mask_matrix)
        else:
            self.data = (users, hists)
        del data, df
        gc.collect()

    def __getitem__(self, idx):
        if self.clicked_mask:
            return self.data[0][idx], self.data[1][idx], self.data[2][idx]
        else:
            return self.data[0][idx], self.data[1][idx]

    def __len__(self):
        return len(self.data[0])

def TestDataLoader(data, clicked_mask=True, click=None, item_nuniq=None, bs=512):
    data_set = TestDataset(data, clicked_mask, click, item_nuniq)
    data_loader = DataLoader(data_set, batch_size=bs, shuffle=False, collate_fn=collate_fn_test)

    return data_loader

### 建模

In [3]:

def seed_torch(seed=42):
    seed = int(seed)
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.enabled = False

seed_torch(1997)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

def label_enc(click, col):
    uniq, nuniq = click[col].unique(), click[col].nunique()
    match = dict(zip(uniq, range(1, nuniq + 1)))
    click[col] = click[col].map(match)

    return click, match, nuniq

def label_enc_test(dic, click, col):
    init_uniq, init_max = dic.keys(), max(dic.values())
    new_uniq = list(set(click[col].unique()).difference(set(init_uniq)))
    dic_ = dict(zip(new_uniq, range(init_max + 1, init_max + 1 + len(new_uniq))))
    new_dic = dic.copy()
    new_dic.update(dic_)
    click[col] = click[col].map(new_dic)
    nuniq = len(new_dic.items())

    return click, new_dic, nuniq, len(new_uniq)

def collate_fn_train(data):
    data.sort(key=lambda x: len(x[1]), reverse=True)
    lens = [len(hist) for _, hist, _ in data]
    users, labels = [], []
    padded_seq = torch.zeros(len(data), max(lens)).long()
    for i, (user, hist, label) in enumerate(data):
        users.append(user)
        padded_seq[i, :lens[i]] = torch.LongTensor(hist)
        labels.append(label)
    # padded_sesss = padded_sesss.transpose(0, 1)

    return users, padded_seq, torch.tensor(labels).long(), lens

def collate_fn_vali(data):
    data.sort(key=lambda x: len(x[1]), reverse=True)
    lens = [len(hist) for _, hist, _, _ in data]
    users, labels = [], []
    padded_seq = torch.zeros(len(data), max(lens)).long()
    click_mask_matrix = []
    for i, (user, hist, label, cmm) in enumerate(data):
        users.append(user)
        padded_seq[i, :lens[i]] = torch.LongTensor(hist)
        labels.append(label)
        click_mask_matrix.append(cmm.reshape(1, -1))
        # click_mask_matrix[i] = cmm
    click_mask_matrix = torch.cat(click_mask_matrix, dim=0)

    return users, padded_seq, torch.tensor(labels).long(), lens, click_mask_matrix

def collate_fn_test(data):
    data.sort(key=lambda x: len(x[1]), reverse=True)
    lens = [len(hist) for _, hist, _ in data]
    users = []
    padded_seq = torch.zeros(len(data), max(lens)).long()
    click_mask_matrix = []
    for i, (user, hist, cmm) in enumerate(data):
        users.append(user)
        padded_seq[i, :lens[i]] = torch.LongTensor(hist)
        click_mask_matrix.append(cmm.reshape(1, -1))
    # padded_sesss = padded_sesss.transpose(0, 1)
    click_mask_matrix = torch.cat(click_mask_matrix, dim=0)

    return users, padded_seq, lens, click_mask_matrix

class Model(nn.Module):

    def __init__(self, n_items, hidden_size, embedding_dim, n_layers=1):
        super(Model, self).__init__()
        self.n_items = n_items
        self.hidden_size = hidden_size
        self.n_layers = n_layers
        self.embedding_dim = embedding_dim
        self.emb = nn.Embedding(self.n_items + 1, self.embedding_dim, padding_idx=0)
        self.emb_dropout = nn.Dropout(0.25) # 0.25
        self.gru = nn.GRU(self.embedding_dim, self.hidden_size, self.n_layers, batch_first=True)
        self.a_1 = nn.Linear(self.hidden_size, self.hidden_size, bias=False)
        self.a_2 = nn.Linear(self.hidden_size, self.hidden_size, bias=False)
        self.v_t = nn.Linear(self.hidden_size, 1, bias=False)
        self.ct_dropout = nn.Dropout(0.5) # 0.5
        self.b = nn.Linear(self.embedding_dim, 2 * self.hidden_size, bias=False)
        # self.sf = nn.Softmax()
        self.device = device

        # self.tanh = nn.Tanh()

    def forward(self, seq, lengths):
        hidden = self.init_hidden(seq.size(0))
        embs = self.emb_dropout(self.emb(seq))
        embs = pack_padded_sequence(embs, lengths, batch_first=True)
        gru_out, hidden = self.gru(embs, hidden)
        gru_out, lengths = pad_packed_sequence(gru_out, batch_first=True)

        # fetch the last hidden state of last timestamp
        ht = hidden[-1]
        # gru_out = gru_out.permute(1, 0, 2)

        c_global = ht
        q1 = self.a_1(gru_out.contiguous().view(-1, self.hidden_size)).view(gru_out.size())
        q2 = self.a_2(ht)
        mask = torch.where(seq > 0, torch.tensor([1.], device=self.device),
                           torch.tensor([0.], device=self.device))
        q2_expand = q2.unsqueeze(1).expand_as(q1)
        q2_masked = mask.unsqueeze(2).expand_as(q1) * q2_expand

        alpha = self.v_t(torch.sigmoid(q1 + q2_masked).view(-1, self.hidden_size)).view(mask.size())
        c_local = torch.sum(alpha.unsqueeze(2).expand_as(gru_out) * gru_out, 1)

        c_t = torch.cat([c_local, c_global], 1)
        c_t = self.ct_dropout(c_t)

        # c_t = self.tanh(c_t)

        item_embs = self.emb(torch.arange(self.n_items + 1).to(self.device))
        scores = torch.matmul(c_t, self.b(item_embs).permute(1, 0))
        # scores = self.sf(scores)

        return scores

    def init_hidden(self, batch_size):
        return torch.zeros((self.n_layers, batch_size, self.hidden_size), requires_grad=True).to(self.device)

class Loss(nn.Module):
    def __init__(self, reg=0, eps=1e-6):
        super(Loss, self).__init__()
        self.reg = reg
        self.eps = eps

    def forward(self, p, n):
        p = torch.exp(p)
        n = torch.exp(n)
        prob = - torch.log(p / (p + torch.sum(n, dim=1, keepdim=True)) + self.eps)

        return prob.sum() + self.reg


def evaluate(rec_matrix, targets, match_num):
    target_repeats = torch.repeat_interleave(targets.view(-1, 1), dim=1, repeats=match_num)
    judge = torch.where(rec_matrix - target_repeats == 0)
    hit = len(judge[0])
    mrr = 0
    ndcg = 0
    for pos in judge[1]:
        mrr += 1 / (pos.float() + 1)
        ndcg += 1 / torch.log2(pos.float() + 2)

    return hit, ndcg, mrr

def Train(train_loader, vali_loader, item_nuniq,
          emb_dim=64, epochs=10, lr=1e-4,
          hidden_size=100, n_layers=1,
          match_num=5, gamma=1e-5, mix_recall_num=50,
          pretrained=False
          ):
    tmp_save_path = './tmp/NARM/'
    model_save = './Model/'
    if not os.path.exists(tmp_save_path):
        os.makedirs(tmp_save_path)
    if not os.path.exists(model_save):
        os.makedirs(model_save)

    print_freq = 500

    if pretrained:
        model = torch.load(model_save + 'narm.pkl')
        # emb_lookup = nn.Embedding(item_nuniq + 1, emb_dim, padding_idx=0)
        pret_emb = torch.zeros(item_nuniq + 1, emb_dim)
        pret_emb[:model.emb.weight.data.shape[0], :] = model.emb.weight.data
        # emb_lookup.weight.data.copy_(pret_emb)
        model.emb = nn.Embedding(item_nuniq + 1, emb_dim, padding_idx=0).to(device)
        model.emb.weight.data.copy_(pret_emb)
        model.n_items = item_nuniq
    else:
        model = Model(item_nuniq, hidden_size, emb_dim, n_layers).to(device)
    num_params = sum(param.numel() for param in model.parameters())

    reg = gamma * num_params
    criterion = nn.CrossEntropyLoss()

    optimizer = torch.optim.Adam(model.parameters(), lr=lr)

    # candidates = torch.Tensor(range(1, item_nuniq + 1)).long().to(device)

    best_mrr = 0
    for epoch in range(epochs):
        if epoch == 0:
            st = time()

        # if epoch == 30 or epoch == 50:
        #     optimizer.param_groups[0]['lr'] = optimizer.param_groups[0]['lr'] * 0.5
        print('========================')
        print('lr:%.4e' % optimizer.param_groups[0]['lr'])

        model.train()
        for i, (user, hist_click, target, lens) in enumerate(train_loader):
            hist_click, target = hist_click.to(device), target.to(device)
            output = model(hist_click, lens)

            loss = criterion(output, target)

            loss.backward()

            # nn.utils.clip_grad_norm_(model.parameters(), max_norm=20, norm_type=2)

            optimizer.step()

            optimizer.zero_grad()

            if i % print_freq == 0:
                print('Epoch: [{0}][{1}/{2}]\t'
                      'Loss {loss:.4f}\t'.format(epoch, i, len(train_loader), loss=loss.item()))

        model.eval()
        HIT, NDCG, MRR = 0, 0, 0
        length = 0
        for user, hist_click, target, lens, clicked_mask in vali_loader:
            hist_click, target = hist_click.to(device), target.to(device)
            candidates_score = F.softmax(model(hist_click, lens)[:, 1:], dim=1)
            # mask clicked
            candidates_score *= clicked_mask.to(device)

            candidate_argsort = candidates_score.argsort(dim=1, descending=True)
            rec_matrix = candidate_argsort[:, :match_num] + 1
            hit, ndcg, mrr = evaluate(rec_matrix, target, match_num)
            length += len(rec_matrix)
            HIT += hit
            NDCG += ndcg
            MRR += mrr

        HIT /= length
        NDCG /= length
        MRR /= length
        print('[+] HIT@{} : {}'.format(match_num, HIT))
        print('[+] NDCG@{} : {}'.format(match_num, NDCG))
        print('[+] MRR@{} : {}'.format(match_num, MRR))
        if best_mrr < MRR:
            best_model = deepcopy(model)
            best_mrr = MRR
            corr_hit, corr_ndcg = HIT, NDCG
            torch.save(best_model, model_save + 'narm.pkl')
            print('Model updated.')
        if epoch == 0:
            et = time()
            print('The last time of 1 epoch: {} min'.format((et - st) / 60))

    print('\n--- Validation Set ---')
    print('[+] HIT@{} : {}'.format(match_num, corr_hit))
    print('[+] NDCG@{} : {}'.format(match_num, corr_ndcg))
    print('[+] Best MRR@{} : {}'.format(match_num, best_mrr))

    # save for offline model fusion
    with torch.no_grad():
        best_model.eval()
        users, targets, match_lst, scores_lst = [], [], [], []
        for user, hist_click, target, lens, clicked_mask in tqdm(vali_loader):
            users += user
            targets += list(target.numpy())
            hist_click, target = hist_click.to(device), target.to(device)
            candidates_score = F.softmax(best_model(hist_click, lens)[:, 1:], dim=1)
            # mask clicked
            candidates_score *= clicked_mask.to(device)
  
            candidate_argsort = candidates_score.argsort(dim=1, descending=True)
            match_lst.append(candidate_argsort[:, :mix_recall_num] + 1)
            scores_lst.append(candidates_score.sort(dim=1, descending=True)[0][:, :mix_recall_num])
  
        match_lst = torch.cat(match_lst, dim=0).cpu().numpy()
        scores_lst = torch.cat(scores_lst, dim=0).cpu().numpy()
        np.savez(tmp_save_path + 'vali.npz', users=users, recall_lst=match_lst, scores_lst=scores_lst, targets=targets)
        print('vali prob saved')
        del match_lst, scores_lst
        gc.collect()

    return best_model


def Inference(model, loader, match_num=50, mix_recall_num=50):
    tmp_save_path = './tmp/NARM/'
    rec_result = []
    users = []
    match_lst, scores_lst = [], []
    with torch.no_grad():
        model.eval()
        for user, hist_click, lens, clicked_mask in tqdm(loader):
            hist_click = hist_click.to(device)
            candidates_score = F.softmax(model(hist_click, lens)[:, 1:], dim=1)
            # mask clicked
            candidates_score *= clicked_mask.to(device)
  
            candidate_argsort = candidates_score.argsort(dim=1, descending=True)
            rec_matrix = candidate_argsort[:, :match_num] + 1
            rec_result.append(rec_matrix)
            match_lst.append(candidate_argsort[:, :mix_recall_num] + 1)
            scores_lst.append(candidates_score.sort(dim=1, descending=True)[0][:, :mix_recall_num])
            users += user
        rec_result = torch.cat(rec_result, dim=0).cpu().numpy()
        users = np.array(users).reshape(-1, 1)
        match_lst = torch.cat(match_lst, dim=0).cpu().numpy()
        scores_lst = torch.cat(scores_lst, dim=0).cpu().numpy()
        np.savez(tmp_save_path + 'test.npz', users=users, recall_lst=match_lst, scores_lst=scores_lst)
        print('test prob saved')
        del match_lst, scores_lst
        gc.collect()

    rec_result = pd.DataFrame(rec_result, columns=['article_{}'.format(i) for i in range(1, match_num + 1)])
    users = pd.DataFrame(users, columns=['user_id'])
    rec_result = pd.concat([users, rec_result], axis=1)

    return rec_result

def ptrain(train_click, # tmp_save_path,
           max_len=3, bs=512, epochs=10,
           lr=1e-4, emb_dim=64, match_num=5,
           gamma=1e-5, hidden_size=100,
           n_layers=1, mix_recall_num=50, valid_num=20000,
          ):
    # train_click = pd.read_csv(train_path)
    global tmp_save_path
    tmp_save_path = './tmp/NARM/'

    dict_save = './dict_tmp/'
    
    if not os.path.exists(tmp_save_path):
        os.makedirs(tmp_save_path)
    
    if not os.path.exists(dict_save):
        os.makedirs(dict_save)

    train_click, user_match, user_nuniq = label_enc(train_click, 'user_id')
    train_click, item_match, item_nuniq = label_enc(train_click, 'click_article_id')
    np.save(dict_save + 'user_dict.npy', user_match)
    np.save(dict_save + 'item_dict.npy', item_match)

    if not os.path.exists(tmp_save_path):
        os.makedirs(tmp_save_path)

    train, vali = construct_samples_train(train_click, max_len=max_len, valid_num=valid_num, model_name='narm')
    train_loader = TrainDataLoader(train, bs)
    vali_loader = ValiDataLoader(vali, clicked_mask=True, click=train_click, item_nuniq=item_nuniq, bs=bs)

    print(torch.cuda.get_device_name(0))

    model = Train(train_loader, vali_loader, item_nuniq, emb_dim=emb_dim,
                  epochs=epochs, lr=lr, match_num=match_num, gamma=gamma,
                  hidden_size=hidden_size, n_layers=n_layers,
                  mix_recall_num=mix_recall_num, pretrained=False
                  )
    del train_loader, vali_loader
    gc.collect()

def ContinueTrainInference(train_click, test_click, emb_dim=64,
              max_len=3, bs=512, epochs=10,
              lr=1e-4, match_num=5, gamma=1e-5,
              hidden_size=100, n_layers=1, mix_recall_num=50
              ):
    dict_save = './dict_tmp/'
    init_user_match, init_item_match = np.load(dict_save + 'user_dict.npy', allow_pickle=True).item(), \
                                       np.load(dict_save + 'item_dict.npy', allow_pickle=True).item()
    test_click, user_match, user_nuniq, new_user_nuniq = label_enc_test(init_user_match, test_click, 'user_id')
    test_click, item_match, item_nuniq, new_item_nuniq = label_enc_test(init_item_match, test_click, 'click_article_id')
    np.save(dict_save + 'user_dict.npy', user_match)
    np.save(dict_save + 'item_dict.npy', item_match)
    train_click['user_id'] = train_click['user_id'].map(user_match)
    train_click['click_article_id'] = train_click['click_article_id'].map(item_match)

    print('New users: {}, items: {}'.format(new_user_nuniq, new_item_nuniq))

    train_ = np.load('./samples_tmp/train_narm.npz', allow_pickle=True)
    train = (train_['users'], train_['seqs'], train_['targets'])
    train, test = construct_samples_test(train, test_click, max_len=max_len)
    valid_ = np.load('./samples_tmp/valid_narm.npz', allow_pickle=True)
    valid = (valid_['users'], valid_['seqs'], valid_['targets'])
    del train_, valid_
    gc.collect()

    train_loader = TrainDataLoader(train, bs)
    vali_loader = ValiDataLoader(valid, clicked_mask=True, click=train_click, item_nuniq=item_nuniq, bs=bs)
    print(torch.cuda.get_device_name(0))

    model = Train(train_loader, vali_loader, item_nuniq, emb_dim=emb_dim,
                  epochs=epochs, lr=lr, match_num=match_num, gamma=gamma,
                  hidden_size=hidden_size, n_layers=n_layers,
                  mix_recall_num=mix_recall_num, pretrained=True
                  )
    del train_loader, vali_loader
    gc.collect()

    test_loader = TestDataLoader(test, clicked_mask=True, click=test_click, item_nuniq=item_nuniq, bs=bs)

    rec_result = Inference(model, test_loader, match_num=match_num, mix_recall_num=mix_recall_num)

    user_rev_match = {v: k for k, v in user_match.items()}
    item_rev_match = {v: k for k, v in item_match.items()}
    rec_result['user_id'] = rec_result.user_id.map(user_rev_match)
    for col in ['article_{}'.format(i) for i in range(1, match_num + 1)]:
        rec_result[col] = rec_result[col].map(item_rev_match)

    rec_result.to_csv('sub_NARM.csv', index=False)
    print(rec_result.head(5))

def pretrain_narm(train_click, epochs):
    emb_dim = 256 # 256
    hidden_size = 512 # 512
    max_len = 18 # 9
    valid_num = 50000
    mix_recall_num = 50

    ptrain(train_click, # tmp_save_path,
           max_len=max_len, bs=512, epochs=epochs,
           lr=1e-4, emb_dim=emb_dim, match_num=5, gamma=1e-5,
           hidden_size=hidden_size, n_layers=1,
           mix_recall_num=mix_recall_num, valid_num=valid_num,
           )

def inference_narm(train_click, test_click, epochs):
    emb_dim = 256 # 256
    hidden_size = 512 # 512
    max_len = 18 # 9
    valid_num = 50000
    mix_recall_num = 50
    ContinueTrainInference(train_click, test_click,
                           max_len=max_len, bs=512, epochs=epochs,
                           lr=1e-4, emb_dim=emb_dim, match_num=5, gamma=1e-5,
                           hidden_size=hidden_size, n_layers=1, mix_recall_num=mix_recall_num
                           )


def load_data(train_path):
    if len(train_path) == 2:
        train_click1 = pd.read_csv(train_path[0])
        train_click2 = pd.read_csv(train_path[1])
        train_click = pd.concat([train_click1, train_click2], axis=0)
    else:
        train_click = pd.read_csv(train_path)
    
    return train_click

# train_path = 'data/train_click_log.csv'
# train_path = ['data/train_click_log.csv', 'data/testA_click_log.csv']
offline = False
if offline:
    data_path = 'offline_data'
else:
    data_path = '/home/stdhi/dataset/exp02/'
train_path = ['{}/train_click_log.csv'.format(data_path), '{}/testA_click_log.csv'.format(data_path)]
train_click = load_data(train_path)
# global tmp_save_path
# tmp_save_path = 'tmp/NARM/'

# Only use train set
ptrain(train_click, # tmp_save_path,
       max_len=max_len, bs=512, epochs=10,
       lr=1e-4, emb_dim=emb_dim, match_num=5, gamma=1e-5,
       hidden_size=hidden_size, n_layers=1,
       mix_recall_num=mix_recall_num, valid_num=valid_num,
       )

# test set
test_path = data_path + 'testA_click_log.csv'
#test_path = 'data/testB_click_log.csv'
test_click = pd.read_csv(test_path)
ContinueTrainInference(train_click, test_click,
                       max_len=max_len, bs=512, epochs=40,
                       lr=1e-4, emb_dim=emb_dim, match_num=5, gamma=1e-5,
                       hidden_size=hidden_size, n_layers=1, mix_recall_num=mix_recall_num
                       )

100%|██████████| 240000/240000 [00:32<00:00, 7378.93it/s]
100%|██████████| 10000/10000 [00:01<00:00, 7475.28it/s]
/opt/py38/lib/python3.8/site-packages/numpy/core/_asarray.py:136: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order, subok=True)

1127329 10000

10000it [00:00, 46010.00it/s]

NVIDIA GeForce GTX 1650
========================
lr:1.0000e-04
Epoch: [0][0/2201]	Loss 29.7671
Epoch: [0][500/2201]	Loss 11.6735
Epoch: [0][1000/2201]	Loss 10.3504
Epoch: [0][1500/2201]	Loss 9.1220
Epoch: [0][2000/2201]	Loss 8.7958
[+] HIT@5 : 0.2746
[+] NDCG@5 : 0.2029043436050415
[+] MRR@5 : 0.17910166084766388

/opt/py38/lib/python3.8/site-packages/torch/serialization.py:401: UserWarning: Couldn't retrieve source code for container of type Model. It won't be checked for correctness upon loading.
  warnings.warn("Couldn't retrieve source code for container of "

Model updated.
The last time of 1 epoch: 4.778305820624033 min
========================
lr:1.0000e-04
Epoch: [1][0/2201]	Loss 8.0254
Epoch: [1][500/2201]	Loss 7.3421
Epoch: [1][1000/2201]	Loss 7.4590
Epoch: [1][1500/2201]	Loss 7.0742
Epoch: [1][2000/2201]	Loss 6.8869
[+] HIT@5 : 0.3199
[+] NDCG@5 : 0.23100706934928894
[+] MRR@5 : 0.20160168409347534
Model updated.
========================
lr:1.0000e-04
Epoch: [2][0/2201]	Loss 6.5138
Epoch: [2][500/2201]	Loss 6.6289
Epoch: [2][1000/2201]	Loss 6.4558
Epoch: [2][1500/2201]	Loss 6.7187
Epoch: [2][2000/2201]	Loss 6.4194
[+] HIT@5 : 0.3386
[+] NDCG@5 : 0.24240441620349884
[+] MRR@5 : 0.21059167385101318
Model updated.
========================
lr:1.0000e-04
Epoch: [3][0/2201]	Loss 6.3720
Epoch: [3][500/2201]	Loss 6.7041
Epoch: [3][1000/2201]	Loss 6.4620
Epoch: [3][1500/2201]	Loss 6.0835
Epoch: [3][2000/2201]	Loss 6.3395
[+] HIT@5 : 0.3467
[+] NDCG@5 : 0.24872809648513794
[+] MRR@5 : 0.2163633555173874
Model updated.
========================
lr:1.0000e-04
Epoch: [4][0/2201]	Loss 5.9979
Epoch: [4][500/2201]	Loss 6.5743
Epoch: [4][1000/2201]	Loss 5.9990
Epoch: [4][1500/2201]	Loss 6.0133
Epoch: [4][2000/2201]	Loss 6.0637
[+] HIT@5 : 0.3551
[+] NDCG@5 : 0.25445756316185
[+] MRR@5 : 0.22123165428638458
Model updated.
========================
lr:1.0000e-04
Epoch: [5][0/2201]	Loss 6.4507
Epoch: [5][500/2201]	Loss 6.1380
Epoch: [5][1000/2201]	Loss 5.9650
Epoch: [5][1500/2201]	Loss 6.0690
Epoch: [5][2000/2201]	Loss 5.8755
[+] HIT@5 : 0.3631
[+] NDCG@5 : 0.25925174355506897
[+] MRR@5 : 0.2249283343553543
Model updated.
========================
lr:1.0000e-04
Epoch: [6][0/2201]	Loss 6.0979
Epoch: [6][500/2201]	Loss 5.9234
Epoch: [6][1000/2201]	Loss 6.0460
Epoch: [6][1500/2201]	Loss 5.9606
Epoch: [6][2000/2201]	Loss 5.8674
[+] HIT@5 : 0.365
[+] NDCG@5 : 0.26064029335975647
[+] MRR@5 : 0.22611331939697266
Model updated.
========================
lr:1.0000e-04
Epoch: [7][0/2201]	Loss 5.8018
Epoch: [7][500/2201]	Loss 5.7921
Epoch: [7][1000/2201]	Loss 5.6295
Epoch: [7][1500/2201]	Loss 5.7248
Epoch: [7][2000/2201]	Loss 5.9692
[+] HIT@5 : 0.3659
[+] NDCG@5 : 0.26233670115470886
[+] MRR@5 : 0.22806501388549805
Model updated.
========================
lr:1.0000e-04
Epoch: [8][0/2201]	Loss 5.6434
Epoch: [8][500/2201]	Loss 5.6954
Epoch: [8][1000/2201]	Loss 5.6968
Epoch: [8][1500/2201]	Loss 5.8118
Epoch: [8][2000/2201]	Loss 5.5171
[+] HIT@5 : 0.3702
[+] NDCG@5 : 0.2655521035194397
[+] MRR@5 : 0.2309499979019165
Model updated.
========================
lr:1.0000e-04
Epoch: [9][0/2201]	Loss 5.7591
Epoch: [9][500/2201]	Loss 5.5656
Epoch: [9][1000/2201]	Loss 5.8195
Epoch: [9][1500/2201]	Loss 5.5734
Epoch: [9][2000/2201]	Loss 5.6537
[+] HIT@5 : 0.3738
[+] NDCG@5 : 0.2672436535358429
[+] MRR@5 : 0.23201501369476318

  0%|          | 0/20 [00:00<?, ?it/s]

Model updated.

--- Validation Set ---
[+] HIT@5 : 0.3738
[+] NDCG@5 : 0.2672436535358429
[+] Best MRR@5 : 0.23201501369476318

100%|██████████| 20/20 [00:06<00:00,  3.11it/s]

vali prob saved
New users: 0, items: 0

FileNotFoundError: [Errno 2] No such file or directory: './samples_tmp/train_narm.npz'

### 获取点击最多的topk个文章

In [28]:
# 获取近期点击最多的文章
def get_item_topk_click(click_df, k):
    topk_click = click_df['click_article_id'].value_counts().index[:k]
    return topk_click

### itemcf的物品相似度计算

In [29]:
def itemcf_sim(df):
    """
        文章与文章之间的相似性矩阵计算
        :param df: 数据表
        :item_created_time_dict:  文章创建时间的字典
        return : 文章与文章的相似性矩阵
        思路: 基于物品的协同过滤(详细请参考上一期推荐系统基础的组队学习)， 在多路召回部分会加上关联规则的召回策略
    """
    
    user_item_time_dict = get_user_item_time(df)
    
    # 计算物品相似度
    i2i_sim = {}
    item_cnt = defaultdict(int)
    for user, item_time_list in tqdm(user_item_time_dict.items()):
        # 在基于商品的协同过滤优化的时候可以考虑时间因素
        for i, i_click_time in item_time_list:
            item_cnt[i] += 1
            i2i_sim.setdefault(i, {})
            for j, j_click_time in item_time_list:
                if(i == j):
                    continue
                i2i_sim[i].setdefault(j, 0)
                
                i2i_sim[i][j] += 1 / math.log(len(item_time_list) + 1)
                
    i2i_sim_ = i2i_sim.copy()
    for i, related_items in i2i_sim.items():
        for j, wij in related_items.items():
            i2i_sim_[i][j] = wij / math.sqrt(item_cnt[i] * item_cnt[j])
    
    # 将得到的相似性矩阵保存到本地
    pickle.dump(i2i_sim_, open(save_path + 'itemcf_i2i_sim.pkl', 'wb'))
    
    return i2i_sim_

i2i_sim = itemcf_sim(all_click_df)

100%|██████████| 10000/10000 [00:00<00:00, 28028.27it/s]

### itemcf 的文章推荐

In [30]:
# 基于商品的召回i2i
def item_based_recommend(user_id, user_item_time_dict, i2i_sim, sim_item_topk, recall_item_num, item_topk_click):
    """
        基于文章协同过滤的召回
        :param user_id: 用户id
        :param user_item_time_dict: 字典, 根据点击时间获取用户的点击文章序列   {user1: [(item1, time1), (item2, time2)..]...}
        :param i2i_sim: 字典，文章相似性矩阵
        :param sim_item_topk: 整数， 选择与当前文章最相似的前k篇文章
        :param recall_item_num: 整数， 最后的召回文章数量
        :param item_topk_click: 列表，点击次数最多的文章列表，用户召回补全        
        return: 召回的文章列表 {item1:score1, item2: score2...}
        注意: 基于物品的协同过滤(详细请参考上一期推荐系统基础的组队学习)， 在多路召回部分会加上关联规则的召回策略
    """
    
    # 获取用户历史交互的文章
    user_hist_items = user_item_time_dict[user_id]
    user_hist_items_ = {user_id for user_id, _ in user_hist_items}
    
    item_rank = {}
    for loc, (i, click_time) in enumerate(user_hist_items):
        for j, wij in sorted(i2i_sim[i].items(), key=lambda x: x[1], reverse=True)[:sim_item_topk]:
            if j in user_hist_items_:
                continue
                
            item_rank.setdefault(j, 0)
            item_rank[j] +=  wij
    
    # 不足10个，用热门商品补全
    if len(item_rank) < recall_item_num:
        for i, item in enumerate(item_topk_click):
            if item in item_rank.items(): # 填充的item应该不在原来的列表中
                continue
            item_rank[item] = - i - 100 # 随便给个负数就行
            if len(item_rank) == recall_item_num:
                break
    
    item_rank = sorted(item_rank.items(), key=lambda x: x[1], reverse=True)[:recall_item_num]
        
    return item_rank

### 给每个用户根据物品的协同过滤推荐文章

In [31]:
# 定义
user_recall_items_dict = collections.defaultdict(dict)

# 获取 用户 - 文章 - 点击时间的字典
user_item_time_dict = get_user_item_time(all_click_df)

# 去取文章相似度
i2i_sim = pickle.load(open(save_path + 'itemcf_i2i_sim.pkl', 'rb'))

# 相似文章的数量
sim_item_topk = 10

# 召回文章数量
recall_item_num = 10

# 用户热度补全
item_topk_click = get_item_topk_click(all_click_df, k=50)

for user in tqdm(all_click_df['user_id'].unique()):
    user_recall_items_dict[user] = item_based_recommend(user, user_item_time_dict, i2i_sim, 
                                                        sim_item_topk, recall_item_num, item_topk_click)

100%|██████████| 10000/10000 [00:04<00:00, 2038.66it/s]

### 召回字典转换成df

In [32]:
# 将字典的形式转换成df
user_item_score_list = []

for user, items in tqdm(user_recall_items_dict.items()):
    for item, score in items:
        user_item_score_list.append([user, item, score])

recall_df = pd.DataFrame(user_item_score_list, columns=['user_id', 'click_article_id', 'pred_score'])

100%|██████████| 10000/10000 [00:00<00:00, 80189.66it/s]

### 生成提交文件

In [38]:
# 生成提交文件
def submit(recall_df, topk=5, model_name=None):
    recall_df = recall_df.sort_values(by=['user_id', 'pred_score'])
    recall_df['rank'] = recall_df.groupby(['user_id'])['pred_score'].rank(ascending=False, method='first')
    
    # 判断是不是每个用户都有5篇文章及以上
    tmp = recall_df.groupby('user_id').apply(lambda x: x['rank'].max())
    #assert tmp.min() >= topk
    
    del recall_df['pred_score']
    submit = recall_df[recall_df['rank'] <= topk].set_index(['user_id', 'rank']).unstack(-1).reset_index()
    
    submit.columns = [int(col) if isinstance(col, int) else col for col in submit.columns.droplevel(0)]
    # 按照提交格式定义列名
    submit = submit.rename(columns={'': 'user_id', 1: 'article_1', 2: 'article_2', 
                                                  3: 'article_3', 4: 'article_4', 5: 'article_5'})
    
    save_name = save_path + model_name + '_' + datetime.today().strftime('%m-%d') + '.csv'
    submit.to_csv(save_name, index=False, header=True)
    
# 获取测试集
tst_click = pd.read_csv(data_path + 'testA_click_log.csv')
tst_users = tst_click['user_id'].unique()

# 从所有的召回数据中将测试集中的用户选出来
tst_recall = recall_df[recall_df['user_id'].isin(tst_users)]

# 生成提交文件
submit(tst_recall, topk=5, model_name='RNN')